<?php

include('get_list_papers.php');


// Area key : Area name
// physicalSystems : Reliable and Secure Communications in Cyber Physical Systems
// denialOfService : Denial-of-Service Attacks and Authentication vs. Network Performance
// networkTopology : Robust, Resilient and Fault-Tolerant Network Topology
// performance : Performance Modeling and Characterization
// mobilityInduced : Mobility-Induced Modeling, Network Dynamics, and Management
// protocol : Protocol Design for Sensor Networks

$papers = array();
$papers[131] = array(
    "type" => "conf",
    "code" => "CP-96",
    "author" => "Yujin Li, Lei Sun, and Wenye Wang",
    "title" => "Exploring Device-to-Device Communication for Mobile Cloud Computing",
    "submission-date" => "",
    "journal/conf" => "in Proc. of the IEEE ICC",
    "vol/pp" => "to appear",
    "venue/date" => "June",
    "year" => "2014",
    "other" => "",
    "doc" => "papers/14LSW-ICC.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[130] = array(
    "type" => "conf",
    "code" => "CP-95",
    "author" => "Sigit Aryo Pambudi and Wenye Wang",
    "title" => "Boundary Matters: Impact of Finite Boundary to Packet Delay Performance in Mobile Data Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of the IEEE ICC",
    "vol/pp" => "to appear",
    "venue/date" => "June",
    "year" => "2014",
    "other" => "",
    "doc" => "papers/14PW-ICC.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[129] = array(
    "type" => "conf",
    "code" => "CP-94",
    "author" => "Yujin Li and Wenye Wang",
    "title" => "Can Mobile Cloudlets Support Mobile Applications",
    "submission-date" => "",
    "journal/conf" => "in Proc. of the IEEE INFOCOM",
    "vol/pp" => "to appear",
    "venue/date" => "April",
    "year" => "2014",
    "other" => "",
    "doc" => "papers/14LW-Info.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[128] = array(
    "type" => "conf",
    "code" => "CP-93",
    "author" => "Mingkui Wei and Wenye Wang",
    "title" => "Greenbench: A Benchmark for Observing Power Grid Vulnerability Under Data-Centric Threats",
    "submission-date" => "",
    "journal/conf" => "in Proc. of the IEEE INFOCOM",
    "vol/pp" => "to appear",
    "venue/date" => "April",
    "year" => "2014",
    "other" => "",
    "doc" => "papers/14WW-Info.pdf",
    "area" => array("physicalSystems")
);
$papers[127] = array(
    "type" => "conf",
    "code" => "CP-92",
    "author" => "Zhuo Lu, Wenye Wang, and Cliff Wang",
    "title" => "How Can Botnets Cause Storms? Understanding the Evolution and Impact of Mobile Botnets",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE INFOCOM",
    "vol/pp" => "to appear",
    "venue/date" => "April",
    "year" => "2014",
    "other" => "",
    "doc" => "papers/14LWW-Info.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[126] = array(
    "type" => "journal",
    "code" => "JP-35",
    "author" => "Zhuo Lu, Wenye Wang, and Cliff Wang",
    "title" => "Camouflage Traffic: Minimizing Message Delay for Smart Grid Applications under Jamming",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Dependable and Secure Communications (TDSC)",
    "vol/pp" => "to appear",
    "venue/date" => "April",
    "year" => "2014",
    "other" => "",
    "doc" => "papers/14lww-TDSC.pdf",
    "bib" => "",
    "area" => array("")
);
$papers[125] = array(
    "type" => "conf",
    "code" => "CP-91",
    "author" => "Mingkui Wei and Wenye Wang",
    "title" => "Toward Distributed Intelligent: A Case Study of Peer to Peer Communication in Smart Grid",
    "submission-date" => "",
    "journal/conf" => "in Proc. of the IEEE GLOBECOM",
    "vol/pp" => "",
    "venue/date" => "December",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/13WW-GB.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[124] = array(
    "type" => "conf",
    "code" => "CP-90",
    "author" => "Lei Sun and Wenye Wang",
    "title" => "Understanding Topology Dynamics in Large-Scale Cognitive Radio Networks under Generic Failures",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE GLOBECOM",
    "vol/pp" => "",
    "venue/date" => "December",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/13SW-GB.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[123] = array(
    "type" => "conf",
    "code" => "CP-89",
    "author" => "Yujin Li and Wenye Wang",
    "title" => "The Unheralded Power of Cloudlet Computing in the Vicinity of Mobile Devices",
    "submission-date" => "",
    "journal/conf" => "in Proc. of the IEEE GLOBECOM",
    "vol/pp" => "",
    "venue/date" => "December",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/13LW-GB.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[122] = array(
    "type" => "conf",
    "code" => "CP-88",
    "author" => "Xiang Lu, Wenye Wang, Jianfeng Ma, and Limin Sun",
    "title" => "Domino of the Smart Grid: An Empirical Study of System Behaviors in the Interdependent Network Architecture",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE SmartGridComm",
    "vol/pp" => "pp. 1-6",
    "venue/date" => "October",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/13LWM-SG.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[121] = array(
    "type" => "journal",
    "code" => "JP-34",
    "author" => "Zhuo Lu, Wenye Wang, and Cliff Wang",
    "title" => "Modeling, Evaluation and Detection of Jamming Attacks against Time-Critical Messages over Wireless in Smart Grid",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Mobile Computing",
    "vol/pp" => "to appear",
    "venue/date" => "October",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/13lww-TMC.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[120] = array(
    "type" => "journal",
    "code" => "JP-33",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "Wireless in Smart Grid: Modeling and Analysis for Time Critical Communications",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Wireless Communications",
    "vol/pp" => "Vol. 12, No. 7, pp. 3360-3371",
    "venue/date" => "July",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/13lzw-TVT.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[119] = array(
    "type" => "journal",
    "code" => "JP-32",
    "author" => "Yujin Li and Wenye Wang",
    "title" => "Inter-Node Mobility Correlation for Group Detection and Analysis in VANETs",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Vehicular Technology",
    "vol/pp" => "Vol. 62, No. 9, pp 4590-4601",
    "venue/date" => "November",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/13lzw-TVT.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[118] = array(
    "type" => "journal",
    "author" => "Yi Xu and Wenye Wang",
    "code" => "JP-31",
    "title" => "Scheduling Partition for Order Optimal Capacity in Large-Scale Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Mobile Computing",
    "vol/pp" => "Vol. 12, No. 4, pp. 666-679",
    "venue/date" => "April",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/13xw-tmc.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[117] = array(
    "type" => "conf",
    "code" => "CP-87",
    "author" => "Lei Sun and Wenye Wang",
    "title" => "Understanding Blackholes in Large-Scale Cognitive Radio Networks Under Generic Failures",
    "submission-date" => "",
    "journal/conf" => "in Proc. of the 32nd Annual IEEE International Conference on Computer Communications (INFOCOM)",
    "vol/pp" => "",
    "venue/date" => "April",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/12sw-IF2.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[116] = array(
    "type" => "conf",
    "code" => "CP-86",
    "author" => "Yujin Li and Wenye Wang",
    "title" => "Horizon on the Move: Geocast in Intermittently Connected Vehicular Ad Hoc Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of the 32nd Annual IEEE International Conference on Computer Communications (INFOCOM)",
    "vol/pp" => "",
    "venue/date" => "April",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/13lw-IF.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[115] = array(
    "type" => "journal",
    "code" => "JP-30",
    "author" => "Xiang Lu, Wenye Wang and Jianfeng Ma",
    "title" => "An Empirical Study of Communication Infrastructure towards the Smart Grid: Design, Implementation, and Evaluation",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Smart Grid",
    "vol/pp" => "Vol. 4, No. 1, pp: 170-183",
    "venue/date" => "March",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/13lwm-TSG.pdf",
    "bib" => "",
    "area" => array("physicalSystems", "denialOfService")
);
$papers[114] = array(
    "type" => "journal",
    "code" => "JP-29",
    "author" => "Zhuo Lu and Wenye Wang",
    "title" => "Cyber Security in the Smart Grid: Survey and Challenges",
    "submission-date" => "",
    "journal/conf" => "Computer Networks",
    "vol/pp" => "pp: 1-28",
    "venue/date" => "January",
    "year" => "2013",
    "other" => "",
    "doc" => "papers/13wl-comnet.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[113] = array(
    "type" => "conf",
    "code" => "CP-85",
    "author" => "Yujin Li, Wenye Wang, and Alexandra Duel-Hallen",
    "title" => "The Latency of Gaining $\alpha$-Reliability for Message Dissemination in Vehicle-to-Vehicle Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE Global Communications Conference (GLOBECOM)",
    "vol/pp" => "",
    "venue/date" => "December",
    "year" => "2012",
    "other" => "",
    "doc" => "papers/12lwd-GB.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[112] = array(
    "type" => "journal",
    "code" => "JP-28",
    "author" => "Zhuo Lu, Wenye Wang, and Cliff Wang",
    "title" => "Modeling and Performance Evaluation of Backoff Misbehaving Nodes in CSMA/CA Networks",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Mobile Computing",
    "vol/pp" => "Vol. 11, No. 8, pp. 1331-1344",
    "venue/date" => "August",
    "year" => "2012",
    "other" => "",
    "doc" => "papers/12lww-tmc.pdf",
    "bib" => "",
    "area" => array("denialOfService")
);
$papers[111] = array(
    "type" => "journal",
    "code" => "JP-27",
    "author" => "Xiang Lu, Wenye Wang and Jianfeng Ma",
    "title" => "Authentication and Integrity in the Smart Grid: An Empirical Study in Substation Automation Systems",
    "submission-date" => "",
    "journal/conf" => "International Journal of Distributed Sensor Networks",
    "vol/pp" => "Vol (2012), Ariticle ID 175262, pp: 1-13",
    "venue/date" => "April",
    "year" => "2012",
    "other" => "",
    "doc" => "papers/12lwm-IJDSN.pdf",
    "bib" => "",
    "area" => array("physicalSystems", "denialOfService")
);
$papers[110] = array(
    "type" => "conf",
    "code" => "CP-84",
    "author" => "Lei Sun and Wenye Wang",
    "title" => "Understanding the Tempo-spatial Limits of Information Dissemination in Multi-channel Cognitive Radio Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of the 31st Annual IEEE International Conference on Computer Communications (INFOCOM)",
    "vol/pp" => "",
    "venue/date" => "April",
    "year" => "2012",
    "other" => "",
    "doc" => "papers/12sw-IF1.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[109] = array(
    "type" => "conf",
    "code" => "CP-83",
    "author" => "Lei Sun and Wenye Wang",
    "title" => "On Latency Distribution and Scaling: From Finite to Large Cognitive Radio Networks under General Mobility",
    "submission-date" => "",
    "journal/conf" => "in Proc. of the 31st Annual IEEE International Conference on Computer Communications (INFOCOM)",
    "vol/pp" => "",
    "venue/date" => "April",
    "year" => "2012",
    "other" => "",
    "doc" => "papers/12sw-IF2.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[108] = array(
    "type" => "conf",
    "code" => "CP-82",
    "author" => "Zhuo Lu, Wenye Wang, and Cliff Wang",
    "title" => "Hiding Traffic with Camouflage: Minimizing Message Delay in the Smart Grid under Jamming",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE INFOCOM Mini-Conference",
    "vol/pp" => "",
    "venue/date" => "April",
    "year" => "2012",
    "other" => "",
    "doc" => "papers/12lww-IF.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[107] = array(
    "type" => "journal",
    "code" => "JP-26",
    "author" => "Ming Zhao, Yujin Li, and Wenye Wang",
    "title" => "Modeling and Analytical Study of Link Properties in Multihop Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Communications",
    "vol/pp" => "Vol. 60, No. 2, pp: 445-456",
    "venue/date" => "February",
    "year" => "2012",
    "other" => "",
    "doc" => "papers/12ZLW-TCOM.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[106] = array(
    "type" => "conf",
    "code" => "CP-81",
    "author" => "Jianhua Zhang, Wenye Wang, Subhashish Bhattacharya",
    "title" => "Architecture of Solid State Transformer-based Energy Router and Energy Traffic",
    "submission-date" => "",
    "journal/conf" => " in Proc. of IEEE/PES 4. innovative Smart Grid Technologies Conference(ISGT)",
    "vol/pp" => "",
    "venue/date" => "January",
    "year" => "2012",
    "other" => "",
    "doc" => "papers/12zwb-ISGT.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[105] = array(
    "type" => "conf",
    "code" => "CP-80",
    "author" => "Yujin Li, Ming Zhao, and Wenye Wang",
    "title" => "Intermittent Connected Vehicle-to-Vehicle Networks: Detection and Analysis",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE GLOBECOM",
    "vol/pp" => "",
    "venue/date" => "December",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11lzw-GB.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[104] = array(
    "type" => "conf",
    "code" => "CP-79",
    "author" => "Haiyang Zheng and Wenye Wang",
    "title" => "On the Access Time in Mobile Hybrid Networks",
    "submission-date" => "",
    "journal/conf" => "",
    "vol/pp" => "",
    "venue/date" => "December",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11zw-GB.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[103] = array(
    "type" => "conf",
    "code" => "CP-78",
    "author" => "Yi Xu, Jianhua Zhang, Wenye Wang, Avik Juneja, and Subhashish Bhattacharya",
    "title" => "Energy Router: Architectures and Functionalities toward Energy Internet",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE SmartGridComm",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11xzw-SG.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[102] = array(
    "type" => "conf",
    "code" => "CP-77",
    "author" => "Xiang Lu and Zhuo Lu and Wenye Wang and Jianfeng Ma",
    "title" => "On Network Performance Evaluation toward the Smart Grid: A Case Study of DNP3 over TCP/IP",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE GLOBECOM",
    "vol/pp" => "",
    "venue/date" => "December",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11llw-GB.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[101] = array(
    "type" => "conf",
    "code" => "CP-76",
    "author" => "Xiang Lu and Wenye Wang and Zhuo Lu and Jianfeng Ma",
    "title" => "From Security to Vulnerability: Data Authentication Undermines Message Delivery in Smart Grid",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE MILCOM",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11lwl-milcom.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[100] = array(
    "type" => "conf",
    "code" => "CP-75",
    "author" => "Xiang Lu and Wenye Wang and Avik Juneja and Alexander Dean",
    "title" => "Talk to Transformers: An Empirical Study of Device Communications for the FREEDM Sysem",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE SmartGridComm",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11lwj-SG.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[99] = array(
    "type" => "conf",
    "code" => "CP-74",
    "author" => "Xiang Lu and Wenye Wang and Zhuo Lu and Jianfeng Ma",
    "title" => "Reliable and Secure Communication Platforms of FREEDM Systems in Smart Grid",
    "submission-date" => "",
    "journal/conf" => "in IEEE MobiCom, Demo Session",
    "vol/pp" => "",
    "venue/date" => "September",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11lwl-mobi.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[98] = array(
    "type" => "conf",
    "code" => "CP-73",
    "author" => "Lei Sun and Wenye Wang",
    "title" => "On Distribution and Limits of Information Dissemination Latency and Speed In Mobile Cognitive Radio Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE INFOCOM, Mini-Conference",
    "vol/pp" => "",
    "venue/date" => "April",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11sw-info.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[97] = array(
    "type" => "conf",
    "code" => "CP-72",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "Information Delivery in Large Wireless Networks with Minimum Energy Expense",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE INFOCOM",
    "vol/pp" => "",
    "venue/date" => "April",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11xw-info.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[96] = array(
    "type" => "conf",
    "code" => "CP-71",
    "author" => "Zhuo Lu and Wenye Wang",
    "title" => "From Jammer to Gambler: Modeling and Detection of Jamming Attacks against Time-Critical Traffic",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE INFOCOM",
    "vol/pp" => "",
    "venue/date" => "April",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11lww-info.pdf",
    "bib" => "",
    "area" => array("denialOfService")
);
$papers[95] = array(
    "type" => "conf",
    "code" => "CP-70",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "The Speed Bounds on Event Reporting in Mobile Sensor Networks with Energy Constraints,",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE ICC",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11xuw-icc.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[94] = array(
    "type" => "conf",
    "code" => "CP-69",
    "author" => "Lei Sun and Wenye Wang",
    "title" => "On the Dissemination Latency of Cognitive Radio Networks Under General Node Mobility",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE ICC",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11sw-icc.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[93] = array(
    "type" => "conf",
    "code" => "CP-68",
    "author" => "Fei Xing and Wenye Wang",
    "title" => "On the User-centric Connection Availability of Mobile Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE ICC",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11xw-icc.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[92] = array(
    "type" => "conf",
    "code" => "CP-67",
    "author" => "Lei Sun and Wenye Wang",
    "title" => "Topology-Incurred Delay for Information Dissemination in Large Multi-Channel Cognitive Radio Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE GLOBECOM",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/10sw-GB.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[91] = array(
    "type" => "journal",
    "code" => "JP-25",
    "author" => "Wenye Wang, Yi Xu, and Mohit Khanna",
    "title" => "A survey on the communication architectures in smart grid",
    "submission-date" => "",
    "journal/conf" => "Computer Networks",
    "vol/pp" => "Vol 55 (2011), pp. 3604-3629",
    "venue/date" => "August",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11wxk-comnet.pdf",
    "bib" => "",
    "area" => array("physicalSystems")
);
$papers[90] = array(
    "type" => "journal",
    "code" => "JP-24",
    "author" => "Fei Xing and Wenye Wang",
    "title" => "Toward Robust Multi-hop Data Forwarding in Large Scale Wireless Network",
    "submission-date" => "",
    "journal/conf" => "Computer Networks",
    "vol/pp" => "Vol 55 (2011), pp. 2608-2621",
    "venue/date" => "May",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11xw-comnet.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[89] = array(
    "type" => "journal",
    "code" => "JP-23",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "The Limit of Information Propagation Speed in Large-Scale Multi-Hop Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "IEEE/ACM Transactions on Networking",
    "vol/pp" => "Vol. 19, No. 1, pp 209-222",
    "venue/date" => "February",
    "year" => "2011",
    "other" => "",
    "doc" => "papers/11xw-ton.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[88] = array(
    "type" => "conf",
    "code" => "CP-66",
    "author" => "Zhuo Lu, Wenye Wang, and Cliff Wang",
    "title" => "Review and Evaluation of Security Threats on the Communication Networks in the SmartGrid",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE Milcom",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2010",
    "other" => "",
    "doc" => "papers/10lw-mil.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[87] = array(
    "type" => "journal",
    "code" => "JP-22",
    "author" => "Avesh K. Agarwal and Wenye Wang",
    "title" => "An Experimental Study of the Performance Impact of Path-based DoS Attacks in Wireless Mesh Networks",
    "submission-date" => "",
    "journal/conf" => "ACM-Springer Mobile Networks and Applications (MONET) Journal",
    "vol/pp" => "Vol. 15, Issue 5, pp. 693-709",
    "venue/date" => "August",
    "year" => "2010",
    "other" => "",
    "doc" => "papers/10aw-monet.pdf",
    "bib" => "",
    "area" => array("physicalSystems", "denialOfService")
);
$papers[86] = array(
    "type" => "journal",
    "code" => "JP-21",
    "author" => "Fei Xing and Wenye Wang",
    "title" => "On the Survivability of Wireless Ad Hoc Networks with Node Misbehaviors and Failures",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Dependable and Secure Computing",
    "vol/pp" => "Vol. 7, No.3, pp. 284-299",
    "venue/date" => "July-September",
    "year" => "2010",
    "other" => "",
    "doc" => "papers/09xw-TDSC.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[85] = array(
    "type" => "conf",
    "code" => "CP-65",
    "author" => "Shawqi Kharbash and Wenye Wang",
    "title" => "All-Terminal Network Reliability Optimization in Fading Environment via Cross Entropy Method",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE ICC",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2010",
    "other" => "",
    "doc" => "papers/10kw-ICC.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[84] = array(
    "type" => "conf",
    "code" => "CP-64",
    "author" => "Zhuo Lu, Cliff Wang, and Wenye Wang",
    "title" => "On the Impact of Backoff Misbehaving Nodes in IEEE 802.11 Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE ICC",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2010",
    "other" => "",
    "doc" => "papers/10lw-ICC.pdf",
    "bib" => "",
    "area" => array("denialOfService")
);
$papers[83] = array(
    "type" => "conf",
    "code" => "CP-63",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "Phase Transition of Traffic Overloading Failures in Large Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE ICC",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2010",
    "other" => "",
    "doc" => "papers/10xw-ICC.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[82] = array(
    "type" => "conf",
    "code" => "CP-62",
    "author" => "Chi Yi and Wenye Wang",
    "title" => "On the Connectivity of Large-Scale Hybrid Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE ICC",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2010",
    "other" => "",
    "doc" => "papers/10yw-ICC.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[81] = array(
    "type" => "conf",
    "code" => "CP-61",
    "author" => "Lei Sun and Wenye Wang",
    "title" => "A Connectivity-Agile Sensing Algorithm for Cognitive Radio Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE ICC",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2010",
    "other" => "",
    "doc" => "papers/10sw-ICC.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[80] = array(
    "type" => "conf",
    "code" => "CP-60",
    "author" => "Chi Yi and Wenye Wang",
    "title" => "On the Connectivity Analysis over Large-Scale Hybrid Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE INFOCOM",
    "vol/pp" => "",
    "venue/date" => "March",
    "year" => "2010",
    "other" => "",
    "doc" => "papers/10yw-IF.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[79] = array(
    "type" => "conf",
    "code" => "CP-59",
    "author" => "Yi Xu and Wenye Wang,",
    "title" => "Characterizing the Spread of Correlated Failures in Large Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE INFOCOM",
    "vol/pp" => "",
    "venue/date" => "March",
    "year" => "2010",
    "other" => "",
    "doc" => "papers/10xw-IF.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[78] = array(
    "type" => "conf",
    "code" => "CP-58",
    "author" => "Zhuo Lu and Wenye Wang",
    "title" => "On Order Gain of Backoff Misbehaving Nodes in CSMA/CA-Based Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE INFOCOM",
    "vol/pp" => "",
    "venue/date" => "March",
    "year" => "2010",
    "other" => "",
    "doc" => "papers/10lw-IF.pdf",
    "bib" => "",
    "area" => array("denialOfService")
);
$papers[77] = array(
    "type" => "conf",
    "code" => "CP-57",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "Localized Scheduling for Practical and Optimal Capacity Utilization in Large Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE GLOBECOM",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2009",
    "other" => "",
    "doc" => "papers/09xw-GB.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[76] = array(
    "type" => "conf",
    "code" => "CP-56",
    "author" => "Lei Sun and Wenye Wang",
    "title" => "On Study of Achievable Capacity with Hybrid Relay in Cognitive Radio Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE GLOBECOM",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2009",
    "other" => "",
    "doc" => "papers/09sw-GB.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[75] = array(
    "type" => "conf",
    "code" => "CP-55",
    "author" => "Avesh K. Agarwal and Wenye Wang",
    "title" => "Performance Sensitivities of Wireless Mesh Networks Under Path-based DoS Attacks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE GLOBECOM",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2009",
    "other" => "",
    "doc" => "papers/09aw-GB.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[74] = array(
    "type" => "conf",
    "code" => "CP-54",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "Scheduling Partitioning for Order Optimal Capacity in Large-Scale Wireelss Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of ACM Mobicom 2009",
    "vol/pp" => "",
    "venue/date" => "September",
    "year" => "2009",
    "other" => "",
    "doc" => "papers/09xw-mc.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[73] = array(
    "type" => "journal",
    "code" => "JP-19",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "Topology Stability Analysis and its Application in Hierarchical Mobile Ad Hoc Networks",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Vehicular Technology",
    "vol/pp" => " Vol.58, No. 3, pp 1546-1560",
    "venue/date" => "March 2009",
    "year" => "2009",
    "other" => "",
    "doc" => "papers/09xw-tvt.pdf",
    "bib" => "",
    "area" => array("networkTopology", "performance")
);
$papers[72] = array(
    "type" => "journal",
    "code" => "JP-20",
    "author" => "Nurcan Tezcan and Wenye Wang",
    "title" => "Self-Orienting Wireless Multimedia Sensor Networks for Occlusion-Free Viewpoints",
    "submission-date" => "",
    "journal/conf" => "Computer Networks, Special issue on Wireless Multimedia Sensor Networks",
    "vol/pp" => "Vol. 52, Issue 14, pp.2558-2567",
    "venue/date" => "May",
    "year" => "2008",
    "other" => "",
    "doc" => "papers/08tw-comnet.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[71] = array(
    "type" => "journal",
    "code" => "JP-18",
    "author" => "Ming Zhao and Wenye Wang",
    "title" => "A Unified Mobility Model for Analysis and Simulation of Mobile Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "ACM-Springer Wireless Networks (WINET)",
    "vol/pp" => "Vol 15, No. 3, pp 365-389",
    "venue/date" => "April",
    "year" => "2009",
    "other" => "",
    "doc" => "papers/09zw-winet.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[70] = array(
    "type" => "conf",
    "code" => "CP-53",
    "author" => "Ming Zhao, Levi Mason, and Wenye Wang",
    "title" => "Empirical Study on Human Mobility for Wireless Mobile Networks",
    "submission-date" => "",
    "journal/conf" => "in Proc. of IEEE Military Communication Conference (Milcom)",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2008",
    "other" => "",
    "doc" => "papers/08zmw-milcom.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[69] = array(
    "type" => "conf",
    "code" => "CP-52",
    "author" => "Fei Xing and Wenye Wang",
    "title" => "On the Critical Phase Transition Time of Wireless Multi-hop Networks with Random Failures",
    "submission-date" => "",
    "journal/conf" => "in Proc. of ACM Mobicom 2008",
    "vol/pp" => "",
    "venue/date" => "September",
    "year" => "2008",
    "other" => "",
    "doc" => "papers/08xw-mc.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[68] = array(
    "type" => "conf",
    "code" => "CP-51",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "Finding the Fastest Path in Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE ICC'2008",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2008",
    "other" => "",
    "doc" => "papers/08xuw-icc.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[67] = array(
    "type" => "conf",
    "code" => "CP-50",
    "author" => "Fei Xing and Wenye Wang",
    "title" => "On the Devolution of Large-scale Sensor Networks in the Presence of Random Failures",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE ICC'2008",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2008",
    "other" => "",
    "doc" => "papers/08xingw-icc.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[66] = array(
    "type" => "conf",
    "code" => "CP-49",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "The Speed of Information Propagation in Large Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE INFOCOM 2008",
    "vol/pp" => "",
    "venue/date" => "April",
    "year" => "2008",
    "other" => "",
    "doc" => "papers/08xw-info.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[65] = array(
    "type" => "conf",
    "code" => "CP-48",
    "author" => "Wenye Wang and Ming Zhao",
    "title" => "Joint Effects of Radio Channels and Node Mobility on Link Dynamics in Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE INFOCOM 2008",
    "vol/pp" => "",
    "venue/date" => "April",
    "year" => "2008",
    "other" => "",
    "doc" => "papers/08wz-info.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[64] = array(
    "type" => "conf",
    "code" => "CP-47",
    "author" => "Nurcan Tezcan and Wenye Wang",
    "title" => "Self-Orienting Wireless Multimedia Sensor Networks for Maximizing Multimedia Coverage",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE ICC'2008",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2008",
    "other" => "",
    "doc" => "papers/08tw-icc.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[63] = array(
    "type" => "conf",
    "code" => "CP-46",
    "author" => "Avesh K. Agarwal, Wenye Wang, Rachana Gupta, and Mo-Yuen Chow",
    "title" => "LAP: Link-Aware Protection for Improving Performance of Loss and Delay Sensitive Applications in Wireless LANs",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Military Communication Conference (Milcom'07)",
    "vol/pp" => "",
    "venue/date" => "Octobe",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07awg-milcom.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[62] = array(
    "type" => "conf",
    "code" => "CP-45",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "Detecting and Mitigating DoS Attacks in Wireless Networks without Affecting the Normal Behaving Nodes",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Military Communication Conference (Milcom'07)",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07xw-milcom.pdf",
    "bib" => "",
    "area" => array("denialOfService")
);
$papers[61] = array(
    "type" => "conf",
    "code" => "CP-44",
    "author" => "Rachana Gupta,  Mo-Yuen Chow, Avesh K. Agarwal, Wenye Wang",
    "title" => "Performance Assessment of Data and Time-Sensitive Wireless Distributed Networked-control-Systems in Presence of Information Securty",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Miltary Communication Conference (Milcom'07)",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2007",
    "other" => "",
    "doc" => "",
    "bib" => "",
    "area" => array("performance")
);
$papers[60] = array(
    "type" => "conf",
    "code" => "CP-43",
    "author" => "Rachana Gupta, Avesh K. Agarwal, Wenye Wang, Mo-Yuen Chow",
    "title" => "Information security with real-time operation: performance assessment for next generation wireless distributed networked-control-systems",
    "submission-date" => "",
    "journal/conf" => "Proc. of 33rd Annual Conference IEEE Industrial Electronics Society",
    "vol/pp" => "pp. 420-425",
    "venue/date" => "",
    "year" => "2007",
    "other" => "",
    "doc" => "",
    "bib" => "",
    "area" => array("performance")
);
$papers[59] = array(
    "type" => "conf",
    "code" => "CP-42",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "Stability of Hierarchical Mobile Ad Hoc Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE GLOBECOM 2007",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07xuw-gc.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[58] = array(
    "type" => "conf",
    "code" => "CP-41",
    "author" => "Ming Zhao and Wenye Wang",
    "title" => "The Impacts of Radio Channels and Node Mobility on Link Statistics in Mobile Ad Hoc Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE GLOBECOM 2007",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07zw-gc.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[57] = array(
    "type" => "conf",
    "code" => "CP-40",
    "author" => "Fei Xing and Wenye Wang",
    "title" => "On the Expected Connection Lifetime and Stochastic Resilience of Wireless Multihop Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE GLOBECOM 2007",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07xingw-gc.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[56] = array(
    "type" => "conf",
    "code" => "CP-39",
    "author" => "Sherry Wang, Harold Zheng, and Wenye Wang",
    "title" => "Efficient Security Management in Ad Hoc Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE GLOBECOM 2007",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2007",
    "other" => "",
    "doc" => "",
    "bib" => "",
    "area" => array("denialOfService")
);
$papers[55] = array(
    "type" => "conf",
    "code" => "CP-38",
    "author" => "Rachana Gupta, Avesh K. Agarwal, Wenye Wang, Mo-Yuen Chow",
    "title" => "Characterization of data-sensitive wireless distributed networked-control-systems",
    "submission-date" => "",
    "journal/conf" => "Proc. of the 2007 IEEE/ASME International Conference on Advanced Intelligent Mechatronics",
    "vol/pp" => "",
    "venue/date" => "September",
    "year" => "2007",
    "other" => "",
    "doc" => "",
    "bib" => "",
    "area" => array("performance")
);

$papers[54] = array(
    "type" => "journal",
    "code" => "JP-17",
    "author" => "Xinbing Wang, Do Young Eun, and Wenye Wang",
    "title" => "A Dynamic TCP-Aware Call Admission Control Scheme for Next Generation Wireless Communications",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Wireless Communications",
    "vol/pp" => "Vol. 6, No. 9, pp 3344-3352",
    "venue/date" => "September",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07wew-twc.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[53] = array(
    "type" => "conf",
    "code" => "CP-37",
    "author" => "Fei Xing and Wenye Wang",
    "title" => "On the Resilient Overlay Topology Formation in Multi-hop Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IFIP Networking 2007",
    "vol/pp" => "",
    "venue/date" => "May",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07xw-net.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[52] = array(
    "type" => "conf",
    "code" => "CP-36",
    "author" => "Fei Xing and Wenye wang",
    "title" => "Analyzing Resilience to Node Misbehaviors in Wireless Multihop Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Wireless Communications and Networking Conference 2007",
    "vol/pp" => "",
    "venue/date" => "March",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07xw-wcnc.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[51] = array(
    "type" => "conf",
    "code" => "CP-35",
    "author" => "Ming Zhao and Wenye Wang",
    "title" => "Analyzing Topology Dynamics in Ad Hoc Networks Using a Smooth Mobility Model",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Wireless Communications and Networking Conference 2007",
    "vol/pp" => "",
    "venue/date" => "March",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07zw-wcnc.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[50] = array(
    "type" => "conf",
    "code" => "CP-34",
    "author" => "Nurcan Tezcan and Wenye Wang",
    "title" => "Effective Coverage and connectivity Preserving in Heterogeneous Sensor Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Wireless Communications and Networking Conference 2007",
    "vol/pp" => "",
    "venue/date" => "March",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07tw-coverage-wcnc.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[49] = array(
    "type" => "conf",
    "code" => "CP-33",
    "author" => "Nurcan Tezcan and Wenye Wang",
    "title" => "Distributed Coordination of Sensors for End-to-End Reliable Event and Query Delivery",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Wireless Communications and Networking Conference 2007",
    "vol/pp" => "",
    "venue/date" => "March",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07tw-reliable-wcnc.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[48] = array(
    "type" => "conf",
    "code" => "CP-32",
    "author" => "Shawqi Kharbash and Wenye Wang",
    "title" => "Computing Two-Terminal Reliability in Mobile Ad hoc Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Wireless Communications and Networking Conference 2007",
    "vol/pp" => "",
    "venue/date" => "March",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07sw-wcnc.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[47] = array(
    "type" => "journal",
    "code" => "JP-16",
    "author" => "Avesh K. Agarwal and Wenye Wang",
    "title" => "On the Impact of Quality of Protection in Wireless Local Area Networks with IP Mobility",
    "submission-date" => "",
    "journal/conf" => "ACM-Springer Mobile Networks and Applications (MONET) Journal",
    "vol/pp" => "Vol. 12, pp. 93-110",
    "venue/date" => "February",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07aw-monet.pdf",
    "bib" => "",
    "area" => array("denialOfService")
);
$papers[46] = array(
    "type" => "journal",
    "code" => "JP-15",
    "author" => "Nurcan Tezcan and Wenye Wang",
    "title" => "ART: An Asymmetric and Reliable Transport Mechanism for Wireless Sensor Networks",
    "submission-date" => "",
    "journal/conf" => "International Journal of Sensor Networks (JSNet)",
    "vol/pp" => "Vol.2, No. 3/4, pp. 188-200",
    "venue/date" => "February",
    "year" => "2007",
    "other" => "",
    "doc" => "papers/07tw-ijsnet.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[45] = array(
    "type" => "conf",
    "code" => "CP-31",
    "author" => "Ming Zhao and Wenye Wang",
    "title" => "A Novel Semi-Markov Smooth Mobility Model for Mobile Ad Hoc Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE GLOBECOM'06, (Best Student Paper Award- Communication Networks)",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/06zw-globecom.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[44] = array(
    "type" => "journal",
    "code" => "JP-14",
    "author" => "Nurcan Tezcan and Wenye Wang",
    "title" => "TTS: A Two-Tiered Scheduling Mechanism for Energy Conservation in Wireless Sensor Networks",
    "submission-date" => "",
    "journal/conf" => "International Journal of Sensor Networks (JSNet)",
    "vol/pp" => "Vol.1, No. 3/4, pp. 213-228",
    "venue/date" => "November 2006",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/06tw-ijsnet.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[43] = array(
    "type" => "journal",
    "code" => "JP-13",
    "author" => "Jungkee Song and Wenye Wang",
    "title" => "A Simulation Study of IP-Based Vertical Handoff in Wireless Convergent Networks",
    "submission-date" => "",
    "journal/conf" => "Wireless Communications and Mobile Computing (WCMC)",
    "vol/pp" => "Vol 6, No. 5, pp 629-650",
    "venue/date" => "July",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/06sw-wcmc.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[42] = array(
    "type" => "journal",
    "code" => "JP-12",
    "author" => "Wenye Wang and Guoliang Xue",
    "title" => "A Cost-Minimization Algorithm for Fast Location Tracking in Mobile Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Computer Networks",
    "vol/pp" => "Vol 50, Issue 15, pp 2713-2726",
    "venue/date" => "October",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/wx06comnet.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[41] = array(
    "type" => "conf",
    "code" => "CP-30",
    "author" => "Yi Xu and Wenye Wang",
    "title" => "MEACA: Mobility and Energy Aware Clustering Algorithm for Constructing Stable MANETs",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Milcom'06",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/06xuw-milcom.pdf",
    "bib" => "",
    "area" => array("networkTopology")
);
$papers[40] = array(
    "type" => "conf",
    "code" => "CP-29",
    "author" => "Avesh K. Agarwal and Wenye Wang",
    "title" => "DSPM: Dynamic Security Policy Management for Optimizing Performance in Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Milcom'06",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/06aw-milcom.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[39] = array(
    "type" => "conf",
    "code" => "CP-28",
    "author" => "Fei Xing and Wenye Wang",
    "title" => "Understanding Dynamic Denial of Service Attacks in Mobile Ad Hoc Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Milcom'06",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/06xw-milcom.pdf",
    "bib" => "",
    "area" => array("denialOfService")
);
$papers[38] = array(
    "type" => "conf",
    "code" => "CP-27",
    "author" => "Ming Zhao and Wenye Wang",
    "title" => "Design and Applications of A Smooth Mobility Model for Mobile Ad Hoc Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Milcom'06",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/06zw-milcom.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[37] = array(
    "type" => "journal",
    "code" => "JP-11",
    "author" => "Wenye Wang, Xinbing Wang, and Arne Nilsson",
    "title" => "Energy-Efficient Bandwidth Allocation in Wireless Networks: Algorithms, Analysis, and Simulation",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Wireless Communications",
    "vol/pp" => "Vol 5, no. 4, pp 1-12",
    "venue/date" => "April",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/wwn06twc.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[36] = array(
    "type" => "conf",
    "code" => "CP-26",
    "author" => "Xinbing Wang, Do Young Eun, and Wenye Wang",
    "title" => "A TCP-Aware Call Admission Control Scheme for Packet-Switched Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE International Performance Computing and Communications Conference (IPCCC)",
    "vol/pp" => "",
    "venue/date" => "April",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/06xew-ipccc.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[35] = array(
    "type" => "conf",
    "code" => "CP-25",
    "author" => "Fei Xing and Wenye Wang",
    "title" => "Modeling and Analysis of Connectivity in Mobile Ad Hoc Networks with Misbehaving Nodes",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE International Conference on Communications (ICC 2006)",
    "vol/pp" => "",
    "venue/date" => "January",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/xw06icc.pdf",
    "bib" => "",
    "area" => array("denialOfService")
);
$papers[34] = array(
    "type" => "conf",
    "code" => "CP-24",
    "author" => "Nurcan Tezcan and Wenye Wang",
    "title" => "TTS: A Two-Tiered Scheduling Algorithm for Wireless Sensor Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE International Conference on Communications (ICC 2006)",
    "vol/pp" => "",
    "venue/date" => "January",
    "year" => "2006",
    "other" => "",
    "doc" => "papers/tw06icc.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[33] = array(
    "type" => "conf",
    "code" => "CP-23",
    "author" => "Avesh Agarwal, Wenye Wang, Janise Y. McNair",
    "title" => "An Experimental Study of Cross-Layer Security Protocols in Public Access Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Global Telecommunications Conference (GLOBECOM'05)",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2005",
    "other" => "",
    "doc" => "papers/aw05gb.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[32] = array(
    "type" => "journal",
    "code" => "JP-10",
    "author" => "Janise McNair, Tuna Tugcu, Wenye Wang, and Jiang Xie",
    "title" => "A Survey of Cross-Layer Performance Enhancements for Mobile IP Networks",
    "submission-date" => "",
    "journal/conf" => "Computer Networks",
    "vol/pp" => "Volume 49, Issue 2, pp119-146",
    "venue/date" => "October",
    "year" => "2005",
    "other" => "",
    "doc" => "papers/mtw05comnet.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);

$papers[31] = array(
    "type" => "conf",
    "code" => "CP-22",
    "author" => "Nurcan Tezcan, Wenye Wang, and Mo-Yuen Chow",
    "title" => "A Bidirectional Transport Mechanism in Wireless Sensor Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of the IEEE MILCOM'05",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2005",
    "other" => "",
    "doc" => "papers/aw05gb.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[30] = array(
    "type" => "conf",
    "code" => "CP-21",
    "author" => "Nurcan Tezcan and Wenye Wang",
    "title" => "A Lightweight Classification Algorithm for Energy Conservation in Wireless Sensor Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of the 14th International Conference on Computer Communication and Networks (ICCCN'05)",
    "vol/pp" => "pp. 87-92",
    "venue/date" => "October",
    "year" => "2005",
    "other" => "",
    "doc" => "papers/tw05ic3.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[29] = array(
    "type" => "conf",
    "code" => "CP-20",
    "author" => "Avesh Agarwal and Wenye Wang",
    "title" => "Statistical Analysis of the Impact of Routing in MANET Based on Real-Time Measurements",
    "submission-date" => "",
    "journal/conf" => "Proc. of the 14th International Conference on Computer Communication and Networks (ICCCN'05)(Nominated for Best Student Paper Award)",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2005",
    "other" => "",
    "doc" => "papers/aw05ic3.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[28] = array(
    "type" => "conf",
    "code" => "CP-19",
    "author" => "Avesh K. Agarwal and Wenye Wang",
    "title" => "Measuring Performance Impact of Security Protocols in Wireless Local Area Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of the 2nd IEEE International Conference on Broadband Networks-- Broadband Wireless Networking Symposium",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2005",
    "other" => "",
    "doc" => "papers/aw05bn.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[27] = array(
    "type" => "journal",
    "code" => "JP-09",
    "author" => "Wenye Wang, Wei Liang, and Avesh K. Agarwal",
    "title" => "Integration of Authentication and Mobility Management in Third Generation and WLAN Data Networks",
    "submission-date" => "",
    "journal/conf" => "Wireless Communications and Mobile Computing (WCMC) - special issue on WLAN/3G Integration for Next-Generation Heterogeneous Mobile Data Networks",
    "vol/pp" => "Volume 5, Issue 6, pp 665-678",
    "venue/date" => "September",
    "year" => "2005",
    "other" => "",
    "doc" => "papers/wla05jwcmc.pdf",
    "bib" => "",
    "area" => array("denialOfService")
);
$papers[26] = array(
    "type" => "journal",
    "code" => "JP-08",
    "author" => "Wei Liang and Wenye Wang",
    "title" => "On Performance Analysis of Challenge/Responds Based Authentication in Wireless Local Area Networks",
    "submission-date" => "",
    "journal/conf" => "Computer Networks (Elsevier)",
    "vol/pp" => "Vol. 48, No. 2, pp 267-288",
    "venue/date" => "June",
    "year" => "2005",
    "other" => "",
    "doc" => "papers/05LW-COMNET.pdf",
    "bib" => "",
    "area" => array("denialOfService")
);

$papers[25] = array(
    "type" => "conf",
    "code" => "CP-18",
    "author" => "Wei Liang, Wenye Wang",
    "title" => "A Quantitative Study of Authentication and QoS in Wireless IP Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE INFOCOM'05",
    "vol/pp" => "",
    "venue/date" => "March",
    "year" => "2005",
    "other" => "",
    "doc" => "papers/05LW-INFOCOM.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[24] = array(
    "type" => "conf",
    "code" => "CP-17",
    "author" => "Wenye Wang, Xinbing Wang, and Arne Nilsson",
    "title" => "A New Admission Control Scheme under Energy and QoS Constraints for Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE INFOCOM'05",
    "vol/pp" => "",
    "venue/date" => "March",
    "year" => "2005",
    "other" => "",
    "doc" => "papers/05WWN-INFOCOM.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[23] = array(
    "type" => "journal",
    "code" => "JP-07",
    "author" => "Ian F. Akyildiz and Wenye Wang",
    "title" => "The Predictive User Mobility Profile Framework for Wireless Multimedia Networks",
    "submission-date" => "",
    "journal/conf" => "IEEE/ACM Transactions on Networking",
    "vol/pp" => "Vol. 12, no. 6, pp. 1021-1035",
    "venue/date" => "December",
    "year" => "2004",
    "other" => "",
    "doc" => "papers/aw04ton.pdf",
    "bib" => "",
    "long-ver-url" => "papers/longToN.pdf",
    "area" => array("mobilityInduced")
);
$papers[22] = array(
    "type" => "conf",
    "code" => "CP-16",
    "author" => "Wei Liang and Wenye Wang",
    "title" => "A Dynamic Security Association Control Scheme for Efficient Authentication in Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Global Telecommunications Conference (GLOBECOM'04)",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2004",
    "other" => "",
    "doc" => "papers/lw04gb.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[21] = array(
    "type" => "conf",
    "code" => "CP-15",
    "author" => "Xinbing Wang and Wenye Wang",
    "title" => "Energy-Aware Call Admission Control Scheme in Wireless Cellular Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Global Telecommunications Conference (GLOBECOM'04)",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2004",
    "other" => "",
    "doc" => "papers/ww04gb.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[20] = array(
    "type" => "conf",
    "code" => "CP-14",
    "author" => "Wei Liang and Wenye Wang",
    "title" => "A Lightweight Authentication Protocol with Local Security Association Control in Mobile Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE MILCOM'04",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2004",
    "other" => "",
    "doc" => "papers/lw04mil.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[19] = array(
    "type" => "conf",
    "code" => "CP-13",
    "author" => "Avesh Agarwal, Jorinjit S. Gill, and Wenye Wang",
    "title" => "Experimental Study of Wireless Security Protocols over Mobile IP Network",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Vehicular Technology Conference 2004 (VTC04 Fall)",
    "vol/pp" => "",
    "venue/date" => "September",
    "year" => "2004",
    "other" => "",
    "doc" => "papers/agw04vtc.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[18] = array(
    "type" => "conf",
    "code" => "CP-12",
    "author" => "Wei Liang and Wenye Wang",
    "title" => "An Analytical Study on the Impact of Authentication in Wireless Local Area Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of the 13th IEEE ICCCN'04, (Best Student Paper Award),",
    "vol/pp" => "",
    "venue/date" => "October",
    "year" => "2004",
    "other" => "",
    "doc" => "papers/lw04ic3n.pdf",
    "bib" => "",
    "area" => array("performance")
);
$papers[17] = array(
    "type" => "conf",
    "code" => "CP-11",
    "author" => "Wei Liang and Wenye Wang",
    "title" => "A Local Authentication Control Scheme Based on AAA Architecture in Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of the 60th IEEE Vehicular Technology Conference (VTC04 Fall)",
    "vol/pp" => "",
    "venue/date" => "September",
    "year" => "2004",
    "other" => "",
    "doc" => "papers/lw04vtc.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[16] = array(
    "type" => "conf",
    "code" => "CP-09",
    "author" => "Xinbing Wang and Wenye Wang",
    "title" => "An Efficient Negotiation Protocol for Real-Time Multimedia Applications Over Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE WCNC04",
    "vol/pp" => "",
    "venue/date" => "March",
    "year" => "2004",
    "other" => "",
    "doc" => "papers/ww04wcnc.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[15] = array(
    "type" => "conf",
    "code" => "CP-10",
    "author" => "Wei Liang and Wenye Wang",
    "title" => "A Cost-Aware Control Scheme for Efficient Authentication in Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of the 15th IEEE International Symposium on Personal, Indoor and Mobile Radio Communications (PIMRC04)",
    "vol/pp" => "",
    "venue/date" => "December",
    "year" => "2004",
    "other" => "",
    "doc" => "papers/lw04pimrc.pdf",
    "bib" => "",
    "area" => array("protocol")
);
$papers[14] = array(
    "type" => "conf",
    "code" => "CP-08",
    "author" => "Wei Liang and Wenye Wang",
    "title" => "A Security Association Management Scheme for Efficient Authentication in Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of World Wireless Congress 2004 (WWC04)",
    "vol/pp" => "pp. 691-696",
    "venue/date" => "May",
    "year" => "2004",
    "other" => "",
    "doc" => "",
    "bib" => "",
    "area" => array("protocol")
);
$papers[13] = array(
    "type" => "conf",
    "code" => "CP-07",
    "author" => "Wenye Wang and Ian F. Akyildiz",
    "title" => "On the Estimation of User Mobility Pattern for Location Tracking in Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE GLOBECOM02",
    "vol/pp" => "",
    "venue/date" => "November",
    "year" => "2002",
    "other" => "",
    "doc" => "papers/02wa-gb.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[12] = array(
    "type" => "journal",
    "code" => "JP-06",
    "author" => "Ian F. Akyildiz and Wenye Wang",
    "title" => "A Dynamic Location Management Scheme for Next Generation Multi-Tier PCS Systems",
    "submission-date" => "",
    "journal/conf" => "IEEE Transactions on Wireless Communications",
    "vol/pp" => ", Vol. 1, No. 1, pp. 178-189",
    "venue/date" => "January",
    "year" => "2002",
    "other" => "",
    "doc" => "papers/wa01jsac.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[11] = array(
    "type" => "journal",
    "code" => "JP-05",
    "author" => "Wenye Wang and Ian F. Akyildiz",
    "title" => "A New Signaling Protocol for Intersystem Roaming in Next-Generation Wireless Systems",
    "submission-date" => "",
    "journal/conf" => "IEEE Journals on Selected Areas in Communications (JSAC)",
    "vol/pp" => "Vol. 19, No. 10, pp. 2040-2052",
    "venue/date" => "October",
    "year" => "2001",
    "other" => "",
    "doc" => "papers/wa01jsac.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[10] = array(
    "type" => "journal",
    "code" => "JP-04",
    "author" => "Wenye Wang, Ian F. Akyildiz, Gordon L. St¨¹ber, and Boo-Young Chung",
    "title" => "Effective Paging Schemes with Delay Bounds as QoS Constraints in Wireless Systems",
    "submission-date" => "",
    "journal/conf" => "ACM-Kluwer Wireless Networks (WINET) Journal",
    "vol/pp" => "Vol. 7, No. 5, pp. 455-466",
    "venue/date" => "September",
    "year" => "2001",
    "other" => "",
    "doc" => "papers/was01page.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[9] = array(
    "type" => "conf",
    "code" => "CP-06",
    "author" => "Ian F. Akyildiz, Wenye Wang, and Young-Jun Lee",
    "title" => "Location Management in 3G/4G Wireless Systems",
    "submission-date" => "",
    "journal/conf" => "Proc. of SPIE - The Convergence of Information Technologies and Communications (ITCom) Conference",
    "vol/pp" => "-",
    "venue/date" => "Denver, August",
    "year" => "2001",
    "other" => "",
    "doc" => "",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[8] = array(
    "type" => "conf",
    "code" => "CP-05",
    "author" => "Wenye Wang and Ian F. Akyildiz",
    "title" => "A Cost Efficient Signaling Protocol for Mobility Application Part (MAP) in IMT 2000 Systems",
    "submission-date" => "",
    "journal/conf" => "Proc. of ACM/IEEE MobiCom'01",
    "vol/pp" => "pp. 345-356",
    "venue/date" => "Rome, Italy, July",
    "year" => "2001",
    "other" => "",
    "doc" => "",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[7] = array(
    "type" => "journal",
    "code" => "JP-03",
    "author" => "Wenye Wang, Ian F. Akyildiz, and Gordon L. St¨¹ber",
    "title" => "An Optimal Partition Algorithm for Minimization of Paging Costs",
    "submission-date" => "",
    "journal/conf" => "IEEE Communications Letters",
    "vol/pp" => "Vol. 5, No. 2, pp. 42-45",
    "venue/date" => "February",
    "year" => "2001",
    "other" => "",
    "doc" => "papers/was01lt.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[6] = array(
    "type" => "conf",
    "code" => "CP-04",
    "author" => "Wenye Wang and Ian F. Akyildiz",
    "title" => "Intersystem Location Update and Paging Schemes for Multitier Wireless Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of ACM/IEEE MobiCom'2000",
    "vol/pp" => "pp. 99-109",
    "venue/date" => "Boston, August",
    "year" => "2000",
    "other" => "",
    "doc" => "papers/00wa-mb.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[5] = array(
    "type" => "conf",
    "code" => "CP-03",
    "author" => "Wenye Wang, Ian F. Akyildiz, and Gordon L. St¨¹ber",
    "title" => "An Optimal Partition Algorithm for Minimization of Paging Costs",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE GLOBECOM 2000",
    "vol/pp" => "Vol. 1, pp. 188-192",
    "venue/date" => "San Francisco, November",
    "year" => "2000",
    "other" => "",
    "doc" => "papers/00was-gb.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[4] = array(
    "type" => "conf",
    "code" => "CP-02",
    "author" => "Wenye Wang, Ian. F Akyildiz, and Gordon L. Stuber",
    "title" => "A Cost Effective Paging Scheme for IMT-2000 Systems",
    "submission-date" => "",
    "journal/conf" => "Proc. of the IEEE Vehicular Technology Conference (IEEE VTC) 2000",
    "vol/pp" => "Vol. 3, pp. 1424-1430",
    "venue/date" => "Boston, September",
    "year" => "2000",
    "other" => "",
    "doc" => "papers/00wa-vtc.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[3] = array(
    "type" => "conf",
    "code" => "CP-01",
    "author" => "Wenye Wang, Ian F. Akyildiz, and Gordon L. St¨¹ber",
    "title" => "Reducing the Paging Costs under Delay Bounds for PCS Networks",
    "submission-date" => "",
    "journal/conf" => "Proc. of IEEE Wireless Communications and Networking Conference (WCNC'2000)",
    "vol/pp" => "Vol. 1, pp. 253-257",
    "venue/date" => "Chicago, September",
    "year" => "2000",
    "other" => "",
    "doc" => "papers/00was-wcnc.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[2] = array(
    "type" => "journal",
    "code" => "JP-02",
    "author" => "Ian F. Akyildiz, Janise McNair, Joseph Ho, Huseyin Uzunalioglu, and Wenye Wang",
    "title" => "Mobility Management for Next Generation Wireless Systems",
    "submission-date" => "",
    "journal/conf" => "Proceedings of the IEEE",
    "vol/pp" => "Vol. 87, No. 8, pp. 1347-1384",
    "venue/date" => "August",
    "year" => "1999",
    "other" => "Nominated for Donald Fink Prize by IEEE Communication Society",
    "doc" => "papers/amh99.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);
$papers[1] = array(
    "type" => "journal",
    "code" => "JP-01",
    "author" => "Ian F. Akyildiz, Janise McNair, Joseph Ho, Huseyin Uzunalioglu, and Wenye Wang",
    "title" => "Mobility Management in Current and Future Communication Networks",
    "submission-date" => "",
    "journal/conf" => "IEEE Network Magazine",
    "vol/pp" => "Vol. 12, No. 8, pp. 39-49",
    "venue/date" => "July/August",
    "year" => "1998",
    "other" => "",
    "doc" => "papers/amh98.pdf",
    "bib" => "",
    "area" => array("mobilityInduced")
);


?>
